package:
  name: lazypredict
  version: 0.2.13  # Replace with the actual version

source:
  url: https://pypi.io/packages/source/l/lazypredict/lazypredict-0.2.13.tar.gz  # Replace with the actual URL

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - scikit-learn
    - pandas
    - numpy

test:
  imports:
    - lazypredict

about:
  home: https://github.com/shankarpandala/lazypredict
  summary: 'Lazy Predict help build a lot of basic models without much code and helps understand which models works better without any parameter tuning'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shankarpandala