name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Update Version in setup.py and __init__.py
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          sed -i "s/version=.*/version='$VERSION',/" setup.py
          sed -i "s/__version__ = .*/__version__ = '$VERSION'/" lazypredict/__init__.py

      - name: Build Package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://upload.pypi.org/legacy/'
      
      - name: Install Conda Build Tool
        run: conda install conda-build

      - name: Build Conda Package
        run: conda-build conda-recipe

      - name: Upload Conda Package
        env:
          ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_TOKEN
          anaconda upload /home/runner/work/lazypredict/lazypredict/conda-bld/noarch/your-conda-package.tar.bz2  # Update with actual package name
